Подключу необходимые библиотеки и файлы

In [1]:
import numpy as np
PI2 = 2 * np.pi

### Упражнение 7.1
В блокноте для этой главы, chap07.ipynb, представлены дополнительные примеры и пояснения. Прочитать блокнот и запустите код.

### Упражнение 7.2
Реализуйте алгоритм Быстрого Преобразования Фурье (БПФ), согласно лемме Дэниелсона-Ланцоша - рекурсивный алгоритм ДПФ. Подробности преобразований, алгоритм и самма лемма представлены в методичке.

### Решение
Начну реализовывать алгоритм, пользуясь подсказками из книги

In [2]:
ys = [-0.2, 0.6, 0.3, -0.7]
hs = np.fft.fft(ys)
print(hs)

[ 0. +0.j  -0.5-1.3j  0.2+0.j  -0.5+1.3j]


In [3]:
def dft(ys):
    N = len(ys)
    ts = np.arange(N) / N
    freqs = np.arange(N)
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    amps = M.conj().transpose().dot(ys)
    return amps

dft(ys)

array([ 0. +0.00000000e+00j, -0.5-1.30000000e+00j,  0.2+2.57175828e-16j,
       -0.5+1.30000000e+00j])

Разделю алгоритм на четные и нечетные элементы

In [4]:
ys[::2] , ys[1::2]

([-0.2, 0.3], [0.6, -0.7])

Сначала реализую нерекурсивный метод

In [5]:
def my_fft(ys):
  He = dft(ys[::2])
  Ho = dft(ys[1::2])
  ns = np.arange(len(ys))
  W = np.exp(-1j * PI2 * ns / len(ys))
  return np.tile(He, 2) + W * np.tile(Ho, 2)

my_fft(ys)

array([ 0. +0.0000000e+00j, -0.5-1.3000000e+00j,  0.2+1.2246468e-17j,
       -0.5+1.3000000e+00j])

Теперь полностью, с рекурсией

In [6]:
def my_fft(ys):
  if len(ys) == 1:
    return ys
  He = my_fft(ys[::2])
  Ho = my_fft(ys[1::2])
  ns = np.arange(len(ys))
  W = np.exp(-1j * PI2 * ns / len(ys))
  return np.tile(He, 2) + W * np.tile(Ho, 2)

In [7]:
my_fft(ys)

array([ 0. +0.0000000e+00j, -0.5-1.3000000e+00j,  0.2+1.2246468e-17j,
       -0.5+1.3000000e+00j])